name: Release mcpscan

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build cross-platform binaries
        run: |
          GOOS=windows GOARCH=amd64 go build -o mcpscan-windows-amd64.exe .
          GOOS=windows GOARCH=arm64 go build -o mcpscan-windows-arm64.exe .
          GOOS=linux GOARCH=amd64 go build -o mcpscan-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o mcpscan-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o mcpscan-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o mcpscan-darwin-arm64 .

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
            name: mcpscan ${{ github.ref_name }}
            draft: true 
            files: mcpscan-*